benchmarks:
  dacapochopin-f480064: [avrora, luindex, xalan, zxing, jme, fop, tomcat, jython,
    batik, cassandra]
configs: [jdk11-gc-frequency-core_ae0b122e-jdk_97f12c2-vm_ca90b43f0f5-mi|ms|s|c2|mmtk_gc-MarkSweep|tph|stress_factor-33554432|num_collect_before_free-16|probes_cp|probes_rustmmtk|probes_native,
  jdk11-gc-frequency-core_ae0b122e-jdk_97f12c2-vm_ca90b43f0f5-mi|ms|s|c2|mmtk_gc-MarkSweep|tph|stress_factor-16777216|num_collect_before_free-16|probes_cp|probes_rustmmtk|probes_native,
  jdk11-gc-frequency-core_ae0b122e-jdk_97f12c2-vm_ca90b43f0f5-mi|ms|s|c2|mmtk_gc-MarkSweep|tph|stress_factor-8388608|num_collect_before_free-16|probes_cp|probes_rustmmtk|probes_native]
heap_range: 6
invocations: 10
minheap_multiplier: 1.0
modifiers:
  c2:
    excludes:
      dacapochopin-29a657f: [tradebeans, tradesoap]
      dacapochopin-f480064: [tradebeans, tradesoap]
    type: JVMArg
    val: -XX:-TieredCompilation -Xcomp
  mmtk_gc: {type: EnvVar, val: '{0}', var: MMTK_PLAN}
  ms: {type: JVMArg, val: '-XX:MetaspaceSize=500M -XX:+DisableExplicitGC'}
  num_collect_before_free: {type: EnvVar, val: '{0}', var: MMTK_NUM_COLLECT_BEFORE_FREE}
  probes_cp: {type: JVMClasspath, val: /root/probes /root/probes/probes.jar}
  probes_native: {type: JVMArg, val: -Djava.library.path=/root/probes}
  probes_rustmmtk: {type: JVMArg, val: -Dprobes=RustMMTk}
  s: {type: JVMArg, val: -server}
  stress_factor: {type: EnvVar, val: '{0}', var: MMTK_STRESS_FACTOR}
  tph: {type: JVMArg, val: '-XX:+UseThirdPartyHeap'}
runtimes:
  jdk11-gc-frequency-core_ae0b122e-jdk_97f12c2-vm_ca90b43f0f5-mi: {home: /root/bench/build/jdk11-gc-frequency-core_ae0b122e-jdk_97f12c2-vm_ca90b43f0f5-mi/images/jdk,
    release: 11, type: OpenJDK}
spread_factor: 1
suites:
  dacapochopin-f480064:
    callback: probe.DacapoChopinCallback
    minheap: temurin-11-G1
    minheap_values:
      temurin-11-G1: {avrora: 65024, batik: 65024, biojava: 65024, cassandra: 65024,
        eclipse: 65024, fop: 65024, graphchi: 65024, h2: 771, h2o: 83, jme: 65024,
        jython: 65024, kafka: 201, luindex: 65024, lusearch: 65024, pmd: 65024, sunflow: 65024,
        tomcat: 65024, tradebeans: 129, tradesoap: 113, xalan: 65024, zxing: 65024}
    path: /root/dacapo/dacapo-evaluation-git-f480064.jar
    release: evaluation
    timeout: 5400
    timing_iteration: 5
    type: DaCapo
